//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id { get; set; }
        public string carNumber { get; set; }
        public int clientId { get; set; }
        public int managerId { get; set; }
        public int statusId { get; set; }
        public decimal price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
